### ISSUE TITLE
what's straight version used with sigproc

### ISSUE THREAD

**Issue by tuanad121** [gillesdegottex/sigproc#1]
I realized that we need straight_mcep and straight_bndap for the best analysis and synthesis quality.
I asked and received the approval for STRAIGHT license from Dr. Kawahara but I'm not sure which version those files coming from. I guess it belongs to C++ version. I came to the site: http://ml.cs.yamanashi.ac.jp/straight/english/download.html which belongs to Dr. Morise who's maintaining C Straight. But I couldn't find those files on the distribution and Dr. Morise said he doesn't know about those files. It makes me confused.
Thanks for spending your time on my issue.
I appreciate it.

**Comment by gillesdegottex** [comment]
Hi,

Unfortunately, I don't see any version information in the one I've been using. It's a C++ version.
The last annotated date of modifications/updates I can find is 2010.

I'm afraid people in parametric TTS haven't been less confused than you about the C++ version of STRAIGHT.

Cheers,

**Comment by tuanad121** [comment]
Thanks for your reply, I appreciate it.
I received the license from Dr. Kawahara.
<img width="737" alt="screen shot 2017-09-04 at 12 01 20 am" src="https://user-images.githubusercontent.com/4689794/30015194-8fe92088-9104-11e7-9149-0bff2f2f4905.png">
All the links from Dr. Kawahara led to Dr. Morise for the C++ version. Unfortunately, Dr. Morise has no idea about the commonly-used version :(
Would you mind sending me the version you used? (dintu@ohsu.edu or tuanad121@gmail.com)
I can compare the performance of STRAIGHT and WORLD inside your vocoder ^^

**Comment by gillesdegottex** [comment]
I would love to know about those differences, but unfortunately I can't send it as it belongs to the University of Cambridge and apparently the license is not flexible on this.

**Comment by tuanad121** [comment]
I see. Thanks for your reply ^^.
